PyTorch is a popular deep learning library that makes it easy to build neural networks and run them on CPUs and GPUs.

In [9]:
pip install torch torchvision torchaudio


Note: you may need to restart the kernel to use updated packages.


In [10]:
import torch
print(torch.__version__)
print("CUDA Available:", torch.cuda.is_available())

2.8.0
CUDA Available: False


In [11]:
import torch

# Create tensors
x = torch.tensor([1, 2, 3])
y = torch.ones(3)  # [1, 1, 1]

print(x + y)       # Tensor addition
print(x * y)       # Element-wise multiplication

# Random tensor
rand = torch.rand(2, 3)
print(rand)

tensor([2., 3., 4.])
tensor([1., 2., 3.])
tensor([[0.0314, 0.3286, 0.5163],
        [0.3745, 0.4504, 0.9760]])


**Automatic Differentiation (Autograd)**
PyTorch can compute gradients automatically.

In [12]:
# Requires gradient tracking
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3 * x + 1
y.backward()  # Compute gradient
print(x.grad) # dy/dx

tensor(7.)


**Building a Neural Network**
We’ll use torch.nn to define layers.

In [13]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2, 4)  # Input=2, Hidden=4
        self.fc2 = nn.Linear(4, 1)  # Output=1

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

net = Net()
print(net)

Net(
  (fc1): Linear(in_features=2, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=1, bias=True)
)
